#!/bin/bash
# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  ##
# Wallust: derive colors from the current wallpaper and update templates
# Usage: WallustSwww.sh [absolute_path_to_wallpaper]

set -euo pipefail

# Inputs and paths
passed_path="${1:-}"
cache_dir="$HOME/.cache/swww/"
rofi_link="$HOME/.config/rofi/.current_wallpaper"
wallpaper_current="$HOME/.config/hypr/wallpaper_effects/.wallpaper_current"

# Helper: get focused monitor name (prefer JSON)
get_focused_monitor() {
	if command -v jq >/dev/null 2>&1; then
		hyprctl monitors -j | jq -r '.[] | select(.focused) | .name'
	else
		hyprctl monitors | awk '/^Monitor/{name=$2} /focused: yes/{print name}'
	fi
}

# Determine wallpaper_path
wallpaper_path=""
if [[ -n "$passed_path" && -f "$passed_path" ]]; then
	wallpaper_path="$passed_path"
else
	# Try to read from swww cache for the focused monitor, with a longer retry loop
	current_monitor="$(get_focused_monitor)"
	cache_file="$cache_dir$current_monitor"

	# Wait for swww to write its cache after an image change (up to 3 seconds)
	for i in {1..30}; do
		if [[ -f "$cache_file" ]]; then
			# Verify the file has content and is not being written
			if [[ -s "$cache_file" ]]; then
				sleep 0.2 # Give it a moment to finish writing
				break
			fi
		fi
		sleep 0.1
	done

	if [[ -f "$cache_file" ]]; then
		# The first non-filter line is the original wallpaper path
		# Use -a to treat as text, suppress binary file warnings
		wallpaper_path="$(grep -a -v 'Lanczos3' "$cache_file" 2>/dev/null | head -n 1)"
	fi
fi

if [[ -z "${wallpaper_path:-}" || ! -f "$wallpaper_path" ]]; then
	# Nothing to do; avoid failing loudly so callers can continue
	exit 0
fi

# Update helpers that depend on the path
ln -sf "$wallpaper_path" "$rofi_link" || true

# CRITICAL FIX: Save the PATH, not the image itself
mkdir -p "$(dirname "$wallpaper_current")"
echo "$wallpaper_path" >"$wallpaper_current" || true

# Run wallust (silent) to regenerate templates defined in ~/.config/wallust/wallust.toml
# -s is used in this repo to keep things quiet and avoid extra prompts
wallust run -s "$wallpaper_path" || true

# --- WAYBAR COLOR FIX ---
# The waybar CSS template is corrupted (dotfiles issue), so we regenerate
# colors-waybar.css manually from the wallust-hyprland.conf output which IS correct.
hypr_colors="$HOME/.config/hypr/wallust/wallust-hyprland.conf"
waybar_colors="$HOME/.config/waybar/wallust/colors-waybar.css"

if [[ -f "$hypr_colors" ]]; then
	# Read colors from hyprland conf (format: $colorN = rgb(RRGGBB))
	get_color() {
		grep -m1 "^\$$1 = rgb(" "$hypr_colors" | sed 's/.*rgb(\(.*\))/\1/'
	}
	bg=$(get_color "background")
	fg=$(get_color "foreground")
	cursor=$(get_color "color8")  # cursor approximated from color8
	c0=$(get_color "color0")
	c1=$(get_color "color1")
	c2=$(get_color "color2")
	c3=$(get_color "color3")
	c4=$(get_color "color4")
	c5=$(get_color "color5")
	c6=$(get_color "color6")
	c7=$(get_color "color7")
	c8=$(get_color "color8")
	c9=$(get_color "color9")
	c10=$(get_color "color10")
	c11=$(get_color "color11")
	c12=$(get_color "color12")
	c13=$(get_color "color13")
	c14=$(get_color "color14")
	c15=$(get_color "color15")

	# Convert rrggbb hex to r,g,b decimal for rgba()
	hex2rgb() {
		local hex="$1"
		printf "%d,%d,%d" "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
	}
	bg_rgb=$(hex2rgb "$bg")

	mkdir -p "$(dirname "$waybar_colors")"
	cat > "$waybar_colors" << EOF
/* ---- Generated by WallustSwww.sh from wallust-hyprland.conf ---- */
@define-color foreground #${fg};
@define-color background #${bg};
@define-color background-alt rgba(${bg_rgb},0.25);
@define-color cursor #${cursor};
@define-color color0 #${c0};
@define-color color1 #${c1};
@define-color color2 #${c2};
@define-color color3 #${c3};
@define-color color4 #${c4};
@define-color color5 #${c5};
@define-color color6 #${c6};
@define-color color7 #${c7};
@define-color color8 #${c8};
@define-color color9 #${c9};
@define-color color10 #${c10};
@define-color color11 #${c11};
@define-color color12 #${c12};
@define-color color13 #${c13};
@define-color color14 #${c14};
@define-color color15 #${c15};
EOF

	# --- SWAYNC COLORS (same source) ---
	swaync_colors="$HOME/.config/swaync/wallust/colors-wallust.css"
	mkdir -p "$(dirname "$swaync_colors")"
	cat > "$swaync_colors" << EOF
/* ---- Generated by WallustSwww.sh from wallust-hyprland.conf ---- */
@define-color text #${fg};
@define-color background rgba(${bg_rgb},0.25);
@define-color background-alt #${bg};
@define-color cursor #${cursor};
@define-color hovered #${c12};
@define-color button-background #${c6};
@define-color button-active #${c2};
@define-color border #${c5};
@define-color urgent #${c15};
EOF

	# --- ROFI COLORS (same source) ---
	rofi_colors="$HOME/.config/rofi/wallust/colors-rofi-generated.rasi"
	mkdir -p "$(dirname "$rofi_colors")"
	cat > "$rofi_colors" << EOF
/* ---- Generated by WallustSwww.sh from wallust-hyprland.conf ---- */
* {
active-background: #${c12};
active-foreground: #${fg};
normal-background: #${bg};
normal-foreground: #${fg};
urgent-background: #${c13};
urgent-foreground: #${fg};
alternate-active-background: #${c11};
alternate-active-foreground: #${fg};
alternate-normal-background: #${bg};
alternate-normal-foreground: #${fg};
alternate-urgent-background: #${bg};
alternate-urgent-foreground: #${fg};
selected-active-background: #${c13};
selected-active-foreground: #${fg};
selected-normal-background: #${c13};
selected-normal-foreground: #${fg};
selected-urgent-background: #${c12};
selected-urgent-foreground: #${fg};
background-color: #${bg};
background: rgba(${bg_rgb},0.7);
foreground: #${fg};
border-color: #${c5};
color0: #${c0};
color1: #${c1};
color2: #${c2};
color3: #${c3};
color4: #${c4};
color5: #${c5};
color6: #${c6};
color7: #${c7};
color8: #${c8};
color9: #${c9};
color10: #${c10};
color11: #${c11};
color12: #${c12};
color13: #${c13};
color14: #${c14};
color15: #${c15};
}
EOF

fi
